# Generated by Django 5.1.3 on 2024-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_data',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=255)),
                ('Registrationdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
