# Generated by Django 5.1.3 on 2024-11-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='updationdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
